title: Documentation
default_lang: en
author:
  name: 'SysEleven GmbH'
  email: openstack@syseleven.de
taxonomies:
  - category
  - tag
metadata:
  description: 'SysEleven Stack Documentation and Tutorials'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
