version: '3'

services:
  docs:
    build: .
    ports:
      - 127.0.0.1:8080:8080
    networks:
      grav_net:
# configure an extra network to ensure that ganalytics `blockedIpRange` is working
# for local development
networks:
  grav_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24
